---

- name: Deploy war file
  hosts: localhost
  become: true
  become_user: root
  tasks:
  - name: Move war file to webapps
    command: mv /var/lib/jenkins/workspace/CICD\ Deployment\ Using\ Ansible\ CM\ Tool/app/target/home.war /var/lib/tomcat9/webapps/home.war
    notify:
      - Restart tomcat9

  handlers:
    - name: Restart tomcat9
      service:
        name: tomcat9
        state: restarted
  
  
...